server {
	listen 80;
	server_name ip24nw1.sit.kmutt.ac.th localhost;

	access_log /var/log/nginx/nw1.access.log main; 

	location / {
		root /usr/share/nginx/html;
		index index.html;
		try_files $uri $uri/ /index.html;
	}

	location /itb-mshop/ {
		proxy_pass http://api-server:8080/nw1/itb-mshop/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
	}

	location /nw1/ {
                alias /usr/share/nginx/html/;
                index index.html;
                try_files $uri $uri/ /index.html;
        }

	location /nw1/itb-mshop/ {
        	proxy_pass http://api-server:8080/nw1/itb-mshop/;
        	proxy_set_header Host $host;
        	proxy_set_header X-Real-IP $remote_addr;
	}
}
