FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_USER=dev
ENV MYSQL_PASSWORD=devpassword
ENV MYSQL_DATABASE=itbms

COPY scripts/ /docker-entrypoint-initdb.d/
COPY my.cnf /etc/mysql/conf.d/my.cnf

EXPOSE 3306
