spring.datasource.url=jdbc:mysql://${DB_URL}:3306/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
server.port=${PORT}
app.cors.allowedHost=${cors_allowed_host}
app.cors.allowedOrigins=${app.cors.allowedHost}
app.base-Url=https://intproj24.sit.kmutt.ac.th/nw1
app.cookie.secure=true
