spring.application.name=Backend
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/itbms
spring.datasource.username=root
spring.datasource.password=xxx
spring.data.jdbc.dialect=mysql
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=UTC
server.error.include-stacktrace=on_param
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.context-path=/nw1/itb-mshop
server.port=8080

file.upload-dir=./images
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.file-size-threshold=512KB
file.support-file-types=image/jpg,image/jpeg,image/png

app.security.jwt.token-max-interval-in-minute=60
app.security.jwt.key-id=IntProj24ItbmsNW1

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=intproj24.nw1@gmail.com
spring.mail.password=otdbbveziokyzlls
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.cors.allowedHost=http://localhost
app.cors.allowedOrigins=${app.cors.allowedHost}:5173
app.base-Url=http://localhost:5173/nw1
