name: Deployment

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: cd & pwd
        run: | 
          cd /NW-1 
          pwd

      - name: checkout & pull
        run: |
          git fetch --all --prune
          git checkout -B release/2.0.0 origin/release/2.0.0

      - name: docker compose
        run: |
          docker compose down -v
          docker compose up -d --build -d
          sleep 20
